# Generated by Django 6.0.4 on 2026-04-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carebot", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExerciseSession",
        ),
    ]